---
title: "Exercies Frecuency Measures and Graphical Representation of Data"
output: html_notebook
---
```{r message=FALSE, warning=FALSE, paged.print=FALSE}

```
# Excercise 2.1 Consider the results of the national elections in South Africa in 2014 and 2009:

Party | Results 2014(%) | Results 2009(%)
--- | --- | ---
ANC | 36.15 | 65.90
DA | 22.23 | 16.66
EFF | 6.35 | - 
IFP | 2.40 | 4.55
COPE | 0.67 | 7.42
Others | 6.20 | 5.47

a. Summarize the results of the 2014 elections in a bar chart. Do it manually and
by using R.
```{r}
exercise2.1 <- data.frame(results2014 = c(62.15, 22.23, 6.35, 2.40, 0.67, 6.20),
                          results2009 = c(65.90, 16.66, NA, 4.55, 7.42, 5.47),
                          row.names = c("ANC", "DA", "EFF", "IFP", "COPE", "Others"))
barplot(exercise2.1$results2014, names.arg = rownames(exercise2.1))
```
b. How would you compare the results of the 2009 and 2014 elections? Offer a
simple solution that can be represented in a single plot. Construct this plot in R.



